spring.application.name=carros

spring.datasource.url=jdbc:postgresql://localhost:5433/loja_carros?useUnicode=true&characterEncoding=UTF-8
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.username=postgres
spring.datasource.password=gabe657

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

server.servlet.encoding.charset=UTF-8
server.servlet.encoding.force=true
spring.http.encoding.charset=UTF-8
spring.http.encoding.enabled=true
spring.http.encoding.force=true

# Static resource handling for uploads
spring.web.resources.static-locations=file:src/main/resources/static/uploads/
spring.mvc.static-path-pattern=/uploads/**
