spring.application.name=carros

spring.datasource.url=jdbc:postgresql://localhost:5433/loja_carros
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.username=postgres
spring.datasource.password=gabe657

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
